fixed missing link
satsummit/satsummit.github.io pull request #102
Opened 2022-08-18 19:05 UTC by kcarini

2022-08-18 21:13 UTC, danielfdsilva requested changes

2022-08-18 21:13 UTC, danielfdsilva commented on content/letter/call-for-lightning-talks.md
> +Our agenda from 2018 SatSummit might be helpful as your shape your session idea. You can find the agenda [here](https://2018.satsummit.io/).
For accessibility purposes it is not ideal to have links ties to words like "here". The link text should reflect what the link is about.

I'd suggest:
```suggestion
Our [agenda from 2018 SatSummit]https://2018.satsummit.io/) might be helpful as your shape your session idea.
```

2022-08-19 13:54 UTC, danielfdsilva approved these changes

2022-08-19 14:05 UTC, ricardoduplos approved these changes

2022-08-19 14:05 UTC, merged